// Code generated automatically; DO NOT EDIT.

package authorizer

var ValidMethods = []string{
	"AddMetadata",
	"Annotate",
	"CloneCollection",
	"CreateCollection",
	"CreateGroup",
	"CreateLabel",
	"CreateProfile",
	"CreateRole",
	"CreateUser",
	"DeleteCollection",
	"DeleteGroup",
	"DeleteImage",
	"DeleteLabel",
	"DeleteMetadata",
	"DeleteProfile",
	"DeleteRole",
	"DeleteUser",
	"FindUser",
	"ImportImage",
	"IngestImage",
	"ListUsers",
	"ReadPolicies",
	"SetPolicies",
	"UpdateCollection",
	"UpdateGroup",
	"UpdateLabel",
	"UpdateMetadata",
	"UpdateRole",
	"UpdateUserPrivileges",
	"*",
}
