// Code generated automatically; DO NOT EDIT.

package authorizer

var validMethods = map[string]struct{}{
	"Annotate": {},
	"AssignRoleToUser": {},
	"AssignUserToGroup": {},
	"ChangePassword": {},
	"CloneCollection": {},
	"CreateCollection": {},
	"CreateGroup": {},
	"CreateLabel": {},
	"CreateRole": {},
	"CreateUser": {},
	"DeleteCollection": {},
	"DeleteGroup": {},
	"DeleteImage": {},
	"DeleteLabel": {},
	"DeleteRole": {},
	"DeleteUser": {},
	"FindUser": {},
	"ImportImage": {},
	"IngestImage": {},
	"ListUsers": {},
	"RenewToken": {},
	"RequestForgottenPasswordToken": {},
	"UnAssignRoleFromUser": {},
	"UnAssignUserFromGroup": {},
	"UpdateCollection": {},
	"UpdateGroup": {},
	"UpdateLabel": {},
	"UpdateRole": {},
	"UpdateUserPrivileges": {},
}
