// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.8.0 DO NOT EDIT.
package models

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AddBoundingBox defines model for AddBoundingBox.
type AddBoundingBox struct {
	// Angle angle of the bounding box
	Angle float32 `json:"angle"`

	// Collection name of collection
	Collection string `json:"collection"`

	// Height height of the bounding box
	Height float32 `json:"height"`

	// ImageId id of image
	ImageId string `json:"imageId"`

	// Label label
	Label string `json:"label"`

	// Width width of the bounding box
	Width float32 `json:"width"`

	// Xc x coordinate of the center point
	Xc float32 `json:"xc"`

	// Yc y coordinate of the center point
	Yc float32 `json:"yc"`
}

// AddPolygon defines model for AddPolygon.
type AddPolygon struct {
	// Collection name of the collection
	Collection string `json:"collection"`

	// ImageId ID of the image
	ImageId string `json:"imageId"`

	// Label Label of the polygon
	Label  string  `json:"label"`
	Points []Point `json:"points"`
}

// BoundingBox defines model for BoundingBox.
type BoundingBox struct {
	// Height height of the bounding box
	Height float32 `json:"height"`

	// Id ID of the bounding box
	Id string `json:"id"`

	// Label label
	Label string `json:"label"`

	// Width width of the bounding box
	Width float32 `json:"width"`

	// Xc x coordinate of the center point
	Xc float32 `json:"xc"`

	// Yc y coordinate of the center point
	Yc float32 `json:"yc"`
}

// CloneCollection defines model for CloneCollection.
type CloneCollection struct {
	// Deep Also clone annotations and meta-data
	Deep *bool `json:"deep,omitempty"`

	// Destination Name of the destination collection
	Destination string `json:"destination"`

	// Group Name of the group of destination collection
	Group *string `json:"group,omitempty"`

	// Source Name of the existing source collection
	Source string `json:"source"`
}

// Collection defines model for Collection.
type Collection struct {
	// Description Description of the collection
	Description *string `json:"description,omitempty"`

	// Group Group of the collection
	Group *string `json:"group,omitempty"`

	// Name Name of the collection
	Name string `json:"name"`

	// Profile Profile of the collection
	Profile *string `json:"profile,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Group defines model for Group.
type Group struct {
	// Description Description of the group
	Description *string `json:"description,omitempty"`

	// Name Name of the group
	Name string `json:"name"`
}

// Image defines model for Image.
type Image struct {
	BoundingBoxes *[]BoundingBox `json:"bounding_boxes,omitempty"`

	// Collection name of collection in which the image belongs
	Collection string `json:"collection"`

	// Id ID of the image
	Id       string                  `json:"id"`
	Labels   *[]string               `json:"labels,omitempty"`
	Meta     *map[string]interface{} `json:"meta,omitempty"`
	Polygons *[]Polygon              `json:"polygons,omitempty"`
}

// ImageIngestionResponse defines model for ImageIngestionResponse.
type ImageIngestionResponse struct {
	// Id ID of ingested image
	Id *string `json:"id,omitempty"`
}

// IngestBoundingBox defines model for IngestBoundingBox.
type IngestBoundingBox struct {
	// Height height of the bounding box
	Height float32 `json:"height"`

	// Label label
	Label string `json:"label"`

	// Width width of the bounding box
	Width float32 `json:"width"`

	// Xc x coordinate of the center point
	Xc float32 `json:"xc"`

	// Yc y coordinate of the center point
	Yc float32 `json:"yc"`
}

// Label defines model for Label.
type Label struct {
	// Description Description of the label
	Description *string `json:"description,omitempty"`

	// Name Name of the label
	Name string `json:"name"`
}

// ListCollections defines model for ListCollections.
type ListCollections struct {
	Collections []Collection `json:"collections"`
	Pagination  Pagination   `json:"pagination"`
}

// ListGroups defines model for ListGroups.
type ListGroups struct {
	Groups []Group `json:"groups"`
}

// ListImages defines model for ListImages.
type ListImages struct {
	Images     []Image    `json:"images"`
	Pagination Pagination `json:"pagination"`
}

// ListLabels defines model for ListLabels.
type ListLabels struct {
	Labels     []Label    `json:"labels"`
	Pagination Pagination `json:"pagination"`
}

// ListUsers defines model for ListUsers.
type ListUsers struct {
	Pagination Pagination `json:"pagination"`
	Users      []User     `json:"users"`
}

// NewCollection defines model for NewCollection.
type NewCollection struct {
	// Description Description of the collection
	Description *string `json:"description,omitempty"`

	// Name Name of the collection
	Name string `json:"name"`
}

// NewGroup defines model for NewGroup.
type NewGroup struct {
	// Description Description of the group
	Description *string `json:"description,omitempty"`

	// Name Name of the group
	Name string `json:"name"`
}

// NewImage defines model for NewImage.
type NewImage struct {
	BoundingBoxes *[]IngestBoundingBox `json:"bounding_boxes,omitempty"`

	// Collection name of collection in which to add the image
	Collection string    `json:"collection"`
	Labels     *[]string `json:"labels,omitempty"`
}

// NewLabel defines model for NewLabel.
type NewLabel struct {
	// Description Description of the label
	Description *string `json:"description,omitempty"`

	// Name Name of the label
	Name string `json:"name"`
}

// NewProfile defines model for NewProfile.
type NewProfile struct {
	// Description Description of the profile
	Description *string `json:"description,omitempty"`

	// Group Group owning the profile
	Group *string `json:"group,omitempty"`

	// Labels Names of the labels the profile allows
	Labels *[]string `json:"labels,omitempty"`

	// Name Name of the profile
	Name string `json:"name"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Groups *[]string `json:"groups,omitempty"`

	// Id Id of the new user
	Id    string    `json:"id"`
	Roles *[]string `json:"roles,omitempty"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// Page current page number
	Page int64 `json:"page"`

	// PageSize maximum number of items per page
	PageSize int `json:"page_size"`

	// TotalItems total number of items
	TotalItems int64 `json:"total_items"`

	// TotalPages total number of pages
	TotalPages int64 `json:"total_pages"`
}

// Point defines model for Point.
type Point = []float32

// Polygon defines model for Polygon.
type Polygon struct {
	// Id ID of the polygon
	Id string `json:"id"`

	// Label Label of the polygon
	Label  string  `json:"label"`
	Points []Point `json:"points"`
}

// Profile defines model for Profile.
type Profile struct {
	// Description Description of the profile
	Description *string `json:"description,omitempty"`

	// Group Group owning the profile
	Group *string `json:"group,omitempty"`

	// Labels Names of the labels the profile allows
	Labels []string `json:"labels"`

	// Name Name of the profile
	Name string `json:"name"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	// Issuer Id of the issuing user
	Issuer string `json:"issuer"`

	// TaskId Id of the generated background task
	TaskId string `json:"task_id"`

	// Type Type of submitted task
	Type string `json:"type"`
}

// UpdateCollection defines model for UpdateCollection.
type UpdateCollection struct {
	// Description New description
	Description *string `json:"description,omitempty"`

	// Group New group
	Group *string `json:"group,omitempty"`

	// Name New name
	Name string `json:"name"`

	// Profile New profile
	Profile *string `json:"profile,omitempty"`
}

// UpdateGroup defines model for UpdateGroup.
type UpdateGroup struct {
	// Description New description of the group
	Description *string `json:"description,omitempty"`

	// Name New name of the group
	Name string `json:"name"`
}

// UpdateProfile defines model for UpdateProfile.
type UpdateProfile struct {
	// Description New description of the profile
	Description *string `json:"description,omitempty"`

	// Group New group owning the profile
	Group *string `json:"group,omitempty"`

	// Labels New label set
	Labels *[]string `json:"labels,omitempty"`

	// Name New name of the profile
	Name string `json:"name"`
}

// User defines model for User.
type User struct {
	Groups []string `json:"groups"`

	// Id Id of the user
	Id    string   `json:"id"`
	Roles []string `json:"roles"`
}

// UserPrivileges defines model for UserPrivileges.
type UserPrivileges struct {
	Groups []string `json:"groups"`
	Roles  []string `json:"roles"`
}

// PageNumber defines model for PageNumber.
type PageNumber = int64

// PageSize defines model for PageSize.
type PageSize = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// FailedDependency defines model for FailedDependency.
type FailedDependency = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnexpectedError defines model for UnexpectedError.
type UnexpectedError = Error

// ListCollectionsParams defines parameters for ListCollections.
type ListCollectionsParams struct {
	// Page page number
	Page *PageNumber `form:"page,omitempty" json:"page,omitempty"`

	// PageSize maximum number of items to return
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListImagesParams defines parameters for ListImages.
type ListImagesParams struct {
	// Page page number
	Page *PageNumber `form:"page,omitempty" json:"page,omitempty"`

	// PageSize maximum number of items to return
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Filter filtering expression
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`

	// Order ordering expression
	Order *string `form:"order,omitempty" json:"order,omitempty"`
}

// IngestImageMultipartBody defines parameters for IngestImage.
type IngestImageMultipartBody struct {
	// Image Raw image data
	Image    openapi_types.File `json:"image"`
	Metadata NewImage           `json:"metadata"`
}

// ListLabelsParams defines parameters for ListLabels.
type ListLabelsParams struct {
	// Page page number
	Page *PageNumber `form:"page,omitempty" json:"page,omitempty"`

	// PageSize maximum number of items to return
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Page page number
	Page *PageNumber `form:"page,omitempty" json:"page,omitempty"`

	// PageSize maximum number of items to return
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// AddBoundingBoxJSONRequestBody defines body for AddBoundingBox for application/json ContentType.
type AddBoundingBoxJSONRequestBody = AddBoundingBox

// AddPolygonJSONRequestBody defines body for AddPolygon for application/json ContentType.
type AddPolygonJSONRequestBody = AddPolygon

// CreateCollectionJSONRequestBody defines body for CreateCollection for application/json ContentType.
type CreateCollectionJSONRequestBody = NewCollection

// CloneCollectionJSONRequestBody defines body for CloneCollection for application/json ContentType.
type CloneCollectionJSONRequestBody = CloneCollection

// UpdateCollectionJSONRequestBody defines body for UpdateCollection for application/json ContentType.
type UpdateCollectionJSONRequestBody = UpdateCollection

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = NewGroup

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = UpdateGroup

// IngestImageMultipartRequestBody defines body for IngestImage for multipart/form-data ContentType.
type IngestImageMultipartRequestBody IngestImageMultipartBody

// CreateLabelJSONRequestBody defines body for CreateLabel for application/json ContentType.
type CreateLabelJSONRequestBody = NewLabel

// CreateProfileJSONRequestBody defines body for CreateProfile for application/json ContentType.
type CreateProfileJSONRequestBody = NewProfile

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = UpdateProfile

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = NewUser

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserPrivileges
